config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/index'
  get 'welcome/about'
  get 'projects/show'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def show
		@projects = Project.all.order(start_date: :desc)
		puts @projects
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sean Wright Professonal Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navigation">
  	<%= link_to 'Home', root_path %> | <%= link_to 'About', welcome_about_path %> | <%= link_to 'Projects', projects_show_path %>

  </div>
    <%= yield %>
  </body>
</html>

app/views/projects/show.html.erb
<h1>Projects</h1>
Here are all of the projects I have done of note! There will always be more to come, and I'll do my best to keep this up to date!
<ul>
<% @projects.each do |project| %>
	<li>
		<h3><%= project.title %></h3>
		<p>
			<a href=<%= project.project_link %>>Link</a><br />
			<%= project.description %>
		</p>
	</li>
<% end %>
</ul>

app/views/welcome/about.html.erb
<div class="collapsible">
	<h2>Background</h2>
	<p>
		I was originally born on the island of O'ahu in the state of Hawaii and grew up there for 18 years. However, I found a passion for building websites after a class at Maryknoll High School, going so far as to find a trial version of Adobe Dreamweaver so that I could continue to make websites. Unfortunately, my other unusual ability to break Windows laptops combined with my past lacking of backing up data (A lesson I've learned the hard way twice now) left all those personal projects to the ether =_=.
	</p>
	<p>
		At the time I was really into drawing anime and manga-style characters, and that was what I initially wanted to pursue. That drive took me to the Unversity of San Francisco in 2008 and culminated in my Bachelor of Fine Arts. You can still see a lot of my art and design work at <a href="http://seanwrightsanfrancisco.carbonmade.com">my online portfolio site</a>.
	</p>
	<p>
		This, however, didn't become realized. While I still enjoy drawing on my free time, I have yet to see myself fully becoming what's known as a "manga-ka". But, I still was able to apply my previous enjoyment of working in HTML and CSS to my work-study position, assisting Michael McCaffrey, the USF School of Management's webmaster at the time.
	</p>
	<p>
		Upon graduation and leaving my extended work-study position in Fall 2012 my next job was at Sparky's Fun and Joy, formerly known as Sparky's Balloons. There I worked for about 2 years as a general crew member, but my role certainly was not so mundane as just working a register. Even now I still know how to twist, assemble, and craft numerous types of ballon characters and sculptures. I even dressed up as a train conductor for a kid's birthday party and helped to make that child's celebration a blast!
	</p>
	<p>
		After working at Sparky's for so long, I worked for about three weeks at ClickAway Mobile, a premium retailer for Verizon Wireless, conveniently located right next to my apartment. This was initially due to my certification as a CompTIA A+ Technician (gained during my sophomore year summer). But shortly after I found a position through Milestone Technologies on the Google Campus through their contract project position as a Common Binary Reviewer (formerly called Unwanted Software Reviewer, which I still think sounds a lot cooler). There I got to work with some amazing people on the really unique location that was the campus, which stretches across the border of Mountain View and Palo Alto. As a plus I learned how to ride a bike within a half hour while there as well! It was a pretty cool gig while it lasted.
	</p>
	<p>
		Sadly, the Google contract was handed over to another vender, and I once again ended up on the job hunt, for the first time without a ongoing job. As much as I try to find something I enjoy, the reality still exists that I needed to make rent somehow. Because of that same certification I gained, I was selected to work as an IT/Operations Support Specialist at LearniT!, a technology training company based here in San Francisco. This was a hybrid role, working both the front desk with the Operations team and in the server room as the on-site member of the IT team. During my almost year at LearniT! I was involved in numerous tasks and projects, taking on more as roles shifted and such. These included tech classroom lab assignment, hardware acquisition and installation, physical storage management, private class catering and other things on top of my initial responsibilities. However, reflectively I ended up taking on more tasks than I could handle, and ended up underperfoming which ultimately ended up in my employment being terminated.
	</p>
	<p>
		After being let go from LearniT! I initially took up my past route of applying to jobs and desperately hoping that someone found enough interest in me to offer me a chance to prove myself. However, after about a month of the usual "spray and pray" I found myself desiring to pursue what I enjoyed in the past, both in high school and in college, which was designing, creating, and maintaining web applications. It was because of this that I took a leap of faith and applied to Dev Bootcamp. To my surprise I was accepted and dedicated 19 weeks to their intensive full-stack engineering program, learning everything that I could about the various aspects of test-driven development, design behaviors, and object-oriented programming. On top of this, I tried to embody what was taught in DBC's "Engineering Empathy" teachings, aiming to be just as much an "actual" person as a programmer.
	</p>
	<p>
		Not only did I learn and practice these various things, I have built actual fully-functoning web applications which can be found on my <a href="https://github.com/nightangelblade/">GitHub</a> and on Heroku. Now I am currently on the job hunt, to see if I can make my first step into the industry and finally follow something that I truly enjoy.
	</p>
	<h2>Me</h2>
	<p>
		Do I consider myself a master of anything that I have learned in the past? Honestly no. A master is something that has spent their entire life dedicated to learning and improving on a craft. I'm still young, and only begun to touch on what can possibly to accomplished through whatever medium, physical, digital, or otherwise. I'm closer to a jack of many trades, but one strong point I consider about myself is that I am a passionate learner. I always want to learn more about something, whether that be new techniques to draw a character, perform a more streamlined jQuery command, or a completely new language (By this I mean both in terms of code and verbal language. I am still learning Japanese and have been taking courses for over six years including college. 面白いか？)
	</p>
	<p>
		At the same time, I feel that the only person I ever feel compelled to compete with is myself. I never aim to get ahead by stepping on other's feet, and I never wish to embody this, whatever reality or other things may seem to dictate. I follow the mentality that "When everyone succeeds, I succeed." and I truly stand by that. Whether on my own or on a team I aim to bring everyone forward while minimalizing conflict.
	</p>
	<p>
		So to summarize myself simply is this: I have learned many things in the past, and I apply those skills to improve myself continuously. I aim to make myself and the others around me better than before. I will always find passion in creating new and amazing things.
	</p>
	<p>
		These are the things that I bring to the table. My question is: <strong>Are you willing to take a chance on me?</strong>
	</p>
</div>

app/views/welcome/index.html.erb
<h1>Sean Wright's Professional Portfolio</h1>
<h2>This is a constant WIP, just like we all are...</h2>
<h2 class="collapsible-title">Introduction</h2>
<p>
	Welcome to my personal website. This serves as a milestone marker of where I've come since my graduation from Dev Bootcamp on February 2017 as a member of the San Francisco Otters cohort.
</p>
<p>
	I hope to accomplish this by continuously building on this website using all of the skills I have learned.
</p>

<div class="collapsible">
	<h2 class="collapsible-title">Technology Learned</h2>
	<ul>
		<li><h3>Test Driven Development</h3></li>
		<ul>
			<li>Ruby</li>
			<ul>
				<li>Rails</li>
				<li>Rack: Sinatra &amp; Shotgun</li>
				<li>RSpec</li>
			</ul>
			<li>JavaScript</li>
			<ul>
				<li>jQuery / AJAX</li>
				<li>three.js</li>
				<li>Jasmine</li>
			</ul>
			<li>Python</li>
		</ul>
		<li><h3>Mobile Development</h3></li>
		<ul>
			<li>React-Native</li>
		</ul>
		<li><h3>Database Management</h3></li>
		<ul>
			<li>SQL</li>
			<li>PostgreSQL</li>
			<li>SQLite3</li>
			<li>ActiveRecord</li>
		</ul>
		<li><h3>Website Design / Development (MVC, MVVM, MVP)</h3></li>
		<ul>
			<li>HTML / HTML5</li>
			<li>CSS / CSS3</li>
			<li>Adobe Creative Suite</li>
		</ul>
		<li><h3>Other Professional Experience</h3></li>
		<ul>
			<li>Certified CompTIA A+ Technician</li>
			<li>Ektron Management System</li>
			<li>Wordpress</li>
			<li>Shopify</li>
		</ul>
	</ul>
</div>